Ych.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ych.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            ViewBag.Infomation = "Everything is Rebuliding";
            return View();
        }



    }
}

Ych.Web/Controllers/LuaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ych.Web.Controllers
{
    public class LuaController : Controller
    {
        //
        // GET: /Lua/

        public ActionResult Index()
        {
            ViewBag.Header = "Everything is Rebuliding by Lua";
            return View();
        }

    }
}

Ych.Web/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver.Builders;
using Ych.Base;
using Ych.Interface;
using Ych.Model;
using Ych.Model.Enum;
using Ych.Service;

namespace Ych.Web.Controllers
{
    public class ManagementController : Controller
    {
        //
        // GET: /Management/


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Articles()
        {
            return View();
        }

        public ActionResult CreateArticle()
        {
            var typeCollection = Ych.Base.MongoDb.Instance.GetCollection<ArticleType>();
            var info = typeCollection.FindAllAs<ArticleType>();
            SelectList selectList = new SelectList(info.ToList(),"TypeId","TypeName");
            ViewBag.TypeList = selectList;
            ViewBag.StatusList = CreateStatusList();
            return View();
        }

        [HttpPost]
        public ActionResult ArticlePost(Article article)
        {
            var collection = Ych.Base.MongoDb.Instance.GetCollection<Article>();
            article.PostDate = DateTime.Now;
            article.IsOpenComment = true;
            //var collection = Ych.Base.MongoDb.Instance.GetCollection<Article>();
            var result = collection.Insert(article);
            return View(result.Ok);
        }

        [HttpPut]
        private SelectList CreateStatusList()
        {
            Dictionary<int,string> statusList= new Dictionary<int, string>();
            statusList.Add(1, "Publish");
            statusList.Add(2, "Delete");
            statusList.Add(3, "Locked");
            statusList.Add(4, "Hidden");
            return new SelectList(statusList,"key","value");
        }

        public ActionResult Accounts()
        {
            return View();
        }

        public ActionResult CreateAccount()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AccountPost(Account account)
        {
            IAccount iAccount = new AccountService();
            account.Password = account.Password.ToPassword();
            return Json(iAccount.CreateAccount(account));
        }

    }
}

Ych.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Here is Ych.im";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="IndexContent">
    <img src="~/Content/Upload/index.jpg" title="W.t.f ?" />
</div>

Ych.Web/Views/Lua/Index.cshtml
@{
    ViewBag.Title = "Ych.im --- Lua";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

Ych.Web/Views/Management/Accounts.cshtml
@{
    ViewBag.Title = "Accounts";
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
}

<h2>Accounts</h2>

Ych.Web/Views/Management/ArticlePost.cshtml
@{
    ViewBag.Title = "ArticlePost";
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
}
@model bool
<h2>Article Post Result</h2>
<div class="Rebuliding">
@if (Model)
{
    <h2>Post Success!</h2>
}
else
{
    <h2>Post Failure!</h2>
}
    
    </div>

Ych.Web/Views/Management/Articles.cshtml
@model List<Ych.Model.Article>

@{
    ViewBag.Title = "Articles";
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
}

<h2>Articles</h2>
@Html.ActionLink("Create New Article", "CreateArticle", "Management")

Ych.Web/Views/Management/CreateAccount.cshtml
@{
    ViewBag.Title = "CreateAccount";
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
}
@model Ych.Model.Account
<h2>CreateAccount</h2>

@using (Html.BeginForm("AccountPost", "Management", FormMethod.Post,new{ id="AccountPost" }))
{
    <fieldset>
        <legend>Create Account</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.LoginName)
                @Html.TextBoxFor(m => m.LoginName)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m=>m.Password)
            </li>

        </ol>
        <input type="submit"  value="Create Account"/>
    </fieldset>
}

@section scripts
{
@*    <script type="text/javascript">

        $("#btnSubmit").click(function () {
            $("#AccountPost").submit(function(e) {
                alert(e);
            });
        });

    </script>*@
}

Ych.Web/Views/Management/CreateArticle.cshtml
@{
    ViewBag.Title = "CreateArticles";
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
}
@model Ych.Model.Article


@using (Html.BeginForm("ArticlePost", "Management", FormMethod.Post))
{
    <fieldset>
        <legend>Create Article</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Title)
                @Html.TextBoxFor(m => m.Title)
            </li>
            <li>
                @Html.LabelFor(m => m.TypeId)
                @Html.DropDownList("TypeId", ViewBag.TypeList as SelectList)
            </li>
            <li>
                @Html.LabelFor(m => m.Content)
                @Html.TextAreaFor(m => m.Content);
            </li>
            <li>
                @Html.LabelFor(m => m.Status)
                @Html.DropDownList("Status", ViewBag.StatusList as SelectList)
            </li>
        </ol>
        <input type="submit" value="更改密码" />
    </fieldset>


}

Ych.Web/Views/Management/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ManagementLayout.cshtml";
}

<h2>Index</h2>

Ych.Web/Views/Shared/BaseMenu.cshtml
<div class="Sidebar">

<h2>@Html.ActionLink("Articles","Articles","Management")</h2>
    <h2>@Html.ActionLink("Accounts","Accounts","Management")</h2>
    </div>

Ych.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="Logo"><span><strong>@ViewBag.Header</strong></span>Base on MVC 4.0</div>
        <div class="Navigation">
            <a href="http://blog.ych.im" target="_blank">Blog</a>
            @Html.ActionLink("Lua","Index","Lua")
            <a href="http://debugger.asia/pmwiki.php" target="_blank">Wiki</a>
        </div>
        <div style="clear: both"></div>
        @RenderBody()

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Ych.Web/Views/Shared/_ManagementLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
    <body>
        @Html.Partial("BaseMenu")
        <div class="Content">
         @RenderBody()   
        </div>
        

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>